### ISSUE TITLE
Error with npm ci

### ISSUE THREAD

**Issue by bennofatius** [Yakabuff/redarc#1]
First off, thanks so much for starting this project. Much appreciated!

I have followed your instructions for Docker installation. The first 3 commands work fine. But then when running the `$ docker build . -t redarc` command, I get the below error.

`ERROR [12/16] RUN npm ci                                                                             0.5s
------
 > [12/16] RUN npm ci:
#0 0.512 npm ERR! code EUSAGE
#0 0.514 npm ERR! 
#0 0.514 npm ERR! The `npm ci` command can only install with an existing package-lock.json or
#0 0.514 npm ERR! npm-shrinkwrap.json with lockfileVersion >= 1. Run an install with npm@5 or
#0 0.514 npm ERR! later to generate a package-lock.json file, then try again.
#0 0.515 npm ERR! 
#0 0.515 npm ERR! Clean install a project
#0 0.515 npm ERR! 
#0 0.515 npm ERR! Usage:
#0 0.515 npm ERR! npm ci
#0 0.515 npm ERR! 
#0 0.515 npm ERR! Options:
#0 0.515 npm ERR! [-S|--save|--no-save|--save-prod|--save-dev|--save-optional|--save-peer|--save-bundle]
#0 0.515 npm ERR! [-E|--save-exact] [-g|--global] [--global-style] [--legacy-bundling]
#0 0.515 npm ERR! [--omit <dev|optional|peer> [--omit <dev|optional|peer> ...]]
#0 0.515 npm ERR! [--strict-peer-deps] [--no-package-lock] [--foreground-scripts]
#0 0.515 npm ERR! [--ignore-scripts] [--no-audit] [--no-bin-links] [--no-fund] [--dry-run]
#0 0.515 npm ERR! [-w|--workspace <workspace-name> [-w|--workspace <workspace-name> ...]]
#0 0.515 npm ERR! [-ws|--workspaces] [--include-workspace-root] [--install-links]
#0 0.515 npm ERR! 
#0 0.515 npm ERR! aliases: clean-install, ic, install-clean, isntall-clean
#0 0.515 npm ERR! 
#0 0.515 npm ERR! Run "npm help ci" for more info
#0 0.516 
#0 0.516 npm ERR! A complete log of this run can be found in:
#0 0.516 npm ERR!     /root/.npm/_logs/2023-06-01T13_12_09_578Z-debug-0.log
------
Dockerfile:16
--------------------
  14 |     
  15 |     RUN mv config_default.json config.json
  16 | >>> RUN npm ci
  17 |     
  18 |     WORKDIR /redarc/redarc-frontend
--------------------
ERROR: failed to solve: process "/bin/sh -c npm ci" did not complete successfully: exit code: 1`

**Comment by Yakabuff** [comment]
package-lock.json was added to my gitignore for some reason.  Gonna fix that

**Comment by Yakabuff** [comment]
@bennofatius I just pushed the changes and tried it on a new machine; seems to build successfully. Can you try running it?

```
/tmp/redarc# docker build . -t redarc
[+] Building 42.7s (21/21) FINISHED                                                                                
 => [internal] load build definition from Dockerfile                                                          0.0s
 => => transferring dockerfile: 536B                                                                          0.0s
 => [internal] load .dockerignore                                                                             0.0s
 => => transferring context: 108B                                                                             0.0s
 => [internal] load metadata for docker.io/library/ubuntu:22.04                                               1.4s
 => [ 1/16] FROM docker.io/library/ubuntu:22.04@sha256:dfd64a3b4296d8c9b62aa3309984f8620b98d87e47492599ee207  1.4s
 => => resolve docker.io/library/ubuntu:22.04@sha256:dfd64a3b4296d8c9b62aa3309984f8620b98d87e47492599ee20739  0.0s
 => => sha256:3b418d7b466ac6275a6bfcb0c86fbe4422ff6ea0af444a294f82d3bf5173ce74 2.30kB / 2.30kB                0.0s
 => => sha256:dbf6a9befcdeecbb8813406afbd62ce81394e3869d84599f19f941aa5c74f3d1 29.53MB / 29.53MB              0.7s
 => => sha256:dfd64a3b4296d8c9b62aa3309984f8620b98d87e47492599ee20739e8eb54fbf 1.13kB / 1.13kB                0.0s
 => => sha256:ca5534a51dd04bbcebe9b23ba05f389466cf0c190f1f8f182d7eea92a9671d00 424B / 424B                    0.0s
 => => extracting sha256:dbf6a9befcdeecbb8813406afbd62ce81394e3869d84599f19f941aa5c74f3d1                     0.6s
 => [internal] load build context                                                                             0.0s
 => => transferring context: 912.00kB                                                                         0.0s
 => [ 2/16] RUN apt-get update && apt-get install -y                                                          4.7s
 => [ 3/16] RUN apt-get install -y curl                                                                       3.6s
 => [ 4/16] RUN apt-get install -y nginx                                                                      4.7s 
 => [ 5/16] RUN apt-get install -y python3                                                                    4.7s 
 => [ 6/16] RUN apt-get install -y postgresql-client                                                          3.8s 
 => [ 7/16] RUN curl -sL https://deb.nodesource.com/setup_16.x | bash - &&     apt-get install -y nodejs     10.9s 
 => [ 8/16] RUN mkdir -p /redarc                                                                              0.4s 
 => [ 9/16] WORKDIR /redarc                                                                                   0.0s 
 => [10/16] COPY . .                                                                                          0.0s 
 => [11/16] RUN mv config_default.json config.json                                                            0.3s 
 => [12/16] RUN npm ci                                                                                        1.5s
 => [13/16] WORKDIR /redarc/redarc-frontend                                                                   0.0s
 => [14/16] RUN npm ci                                                                                        3.9s
 => [15/16] WORKDIR /redarc                                                                                   0.0s
 => [16/16] RUN chmod +x scripts/start.sh                                                                     0.3s
 => exporting to image                                                                                        1.2s
 => => exporting layers                                                                                       1.2s
 => => writing image sha256:aa081d91a78f6dbab4fa04274d8d7a47c19139c5753e9877a0581de0ee59bbd3                  0.0s
 => => naming to docker.io/library/redarc  
```

**Comment by bennofatius** [comment]
This step has worked now, thanks so much!
