### ISSUE TITLE
Add r/libreal, r/conservative to UI?

### ISSUE THREAD

**Issue by josh-ashkinaze** [Yakabuff/redarc#14]
A lot of academic research on Reddit involves political stuff. I know the UI is mainly supposed to be a demo, but if you are going to add a few more subreddits those might be interesting contenders.

Thanks so much for making and maintaining this -- really awesome project and super impressive progress so far!

**Comment by matt-mich** [comment]
The project itself should stay apolitical by default. You can always run your own instance if you'd like that contains the archive of all relevant political Subreddits, and provide the link to that instance to the research community. The point of this project is to provide an interface to interact with an archive of Reddit data. Additionally, if the demo were providing useful tools for researchers, it would cost a significant amount of money to maintain as more people used it. It's for the best that the demo just shows the current state of the UI, so you can see if you want to put the effort in to running your own instance.
