### ISSUE TITLE
Using API

### ISSUE THREAD

**Issue by bennofatius** [Yakabuff/redarc#3]
Sorry this may not be an issue but just a very basic question. I have now successfully built with docker, and I do see the Redarc site when opening localhost. However, I'm not sure how exactly to query things. Based on your API instructions, I tried things like this:

`http://localhost/api/search/comments?body=love`

But this would always result in an 'Internal Server Error'. Any help would be much appreciated!

**Comment by Yakabuff** [comment]
http://redarc.basedbin.org/api/search/comments?body=love

Seems to work on my instance

Can you verify your postgres connection?

**Comment by Yakabuff** [comment]
`docker exec -it redarc bash`

`psql -h pgsql-dev -U postgres -a`

**Comment by bennofatius** [comment]
This is what I get when running the commands you suggested:

`psql (14.8 (Ubuntu 14.8-0ubuntu0.22.04.1), server 15.3 (Debian 15.3-1.pgdg110+1))
WARNING: psql major version 14, server major version 15.
         Some psql features might not work.
Type "help" for help.`

**Comment by bennofatius** [comment]
Btw I no longer get 'Internal Server Error' but just an empty array, even when searching for comments with the most generic keywords such as 'and'

**Comment by Yakabuff** [comment]
@bennofatius Yes, the keyword search is quite primitive atm;  it only supports exact matches.  I'm working on integrating elasticsearch/postgres full-text search

**Comment by bennofatius** [comment]
Oh ok got it, thanks

**Comment by Yakabuff** [comment]
Just FYI, search is implemented

http://redarc.basedbin.org/search

**Comment by bennofatius** [comment]
Awesome, will try and let you know!

**Comment by Yakabuff** [comment]
only /r/iphone and /r/datahoarder is searchable at the moment btw

**Comment by bennofatius** [comment]
ah ok, no subreddit agnostic comment search yet? that'd be the killer use case for me :)
