### ISSUE TITLE
KeyError: 'gilded'

### ISSUE THREAD

**Issue by ohhdemgirls** [Yakabuff/redarc#4]
```
Traceback (most recent call last):
  File "/home/red/redarc_docker/redarc/scripts/load_sub.py", line 33, in <module>
    gilded = sub_dict['gilded']
KeyError: 'gilded'
```

When entering `AskReddit_submissions`

**Comment by Yakabuff** [comment]
Pushshift data isn't normalized and there are inconsistencies sometimes.  Working on a fix

**Comment by Yakabuff** [comment]
https://github.com/Yakabuff/redarc/commit/5da45f2abcc2130bf4cb93e009cac149dbd2caa9

This commit should fix it.  Let me know if that works for you

**Comment by Yakabuff** [comment]
@ohhdemgirls

**Comment by ohhdemgirls** [comment]
Prefect, thanks. Seems to be working, going to take awhile to get everything imported mind you :rofl:

**Comment by ohhdemgirls** [comment]
Spoke too soon, same file failed differently toward the end... 

```
Identifier inserted succesfully x9zhzi
====================
ERROR: A string literal cannot contain NUL (0x00) characters.
```

(also spelling typo in your code :stuck_out_tongue_closed_eyes: )

**Comment by Yakabuff** [comment]
Working on a fix.  I'm also considering removing the SQL rollback; it's not ideal to have to reinsert every submission/comment after an error especially for very large dump files

**Comment by ohhdemgirls** [comment]
> it's not ideal to have to reinsert every submission/comment after an error especially for very large dump files

True, once I'm able to get everything into the DB it's going to take some tuning for it to be lean but I've already provisioned all nvme storage and a terabyte of ram for it so we should be able to host a static historical version of what PS had available on it's API before people started wanting things removed and reddit nuked it!

There's going to be more edge cases in this data I'm sure so I'm very glad you're able to put in some time wrangling it, get on discord if you want to knock heads on this. Realizing who you are I've been a fan of your previous works :ok_hand:

**Comment by Yakabuff** [comment]
I completely revamped the scripts. It now tries to insert everything first and then logs the problematic rows.

**Comment by Yakabuff** [comment]
I also added `.replace("\u0000", "")` to handle null characters in user submitted fields like selftext and title

**Comment by Yakabuff** [comment]
@ohhdemgirls

**Comment by ohhdemgirls** [comment]
`real    383m8.352s`

Worked that time, but now lets work on speeding up ingest if possible :yum:

**Comment by ohhdemgirls** [comment]
`real    383m8.352s`

Worked that time, but now lets work on speeding up ingest if possible :yum:

**Comment by Yakabuff** [comment]
It's the print statements that's making it slow.  Btw, did you check the log file for any warnings/errors
