### ISSUE TITLE
Correct API search capitalization

### ISSUE THREAD

**Issue by ohhdemgirls** [Yakabuff/redarc#5]
When I first setup I was checking `submissions?author=-Archivist` and it worked, 
but now I have to use `submissions?author=-archivist` (lower case A) 

The same with subs `subreddit=AskReddit` it's now `subreddit=askreddit` 

I think this is breaking, while reddit ignores capitalization it returns pages for both upper and lower, so your api should too for when people copy paste things as they are on reddit, examples......
```
https://old.reddit.com/user/-archivist/
https://old.reddit.com/user/-Archivist/
https://old.reddit.com/r/askreddit/ (actually corrects/redirs)
https://old.reddit.com/r/AskReddit/
```

Suggested fix would be to support both ideally given inconsistencies in ps data.

**Comment by Yakabuff** [comment]
Funnily enough, the changes I made were actually to normalize inconsistent pushshift data which in theory should actually fix the issue you're having.  I changed the ingest scripts to insert subreddit and author as lowercase and changed the API to convert all query parameters to lowercase so it works regardless of capitalization.

What's odd is that I can't replicate the issue you're having

On the most recent commit (new api and fresh database from new script), it works as intended and it is case insensitive.  Data is all lowercase and API turns all query params to lowercase as well

On the new API but with an older database where capitalization was not normalized, no queries work (both lowercase and normal capitalization) which is also expected as the subreddit/author are not lowercase in the database even if the API turns all query params to lowercase

The only scenario where only lowercase works is if you somehow ingested data with the new ingest scripts from the most recent commit but also somehow still using the old API?  Maybe you need to rebuild the image/rerun the container?

Unlike mysql where everything is case-insensitive by default, there is no clear-cut way of doing this on postgres.  We could use lower() but that inhibits us from using indexes in the future and also affects performance

**Comment by ohhdemgirls** [comment]
You were right, I just re-rolled and it's fixed.
